.TH HASH 1 "25 May 2023" "HASH v1.0" "General Commands Manual"
.SH NAME
hash \- Hack Again SHell
.SH SYNOPSIS
.B hash
[\fBOPTIONS\fR]
[\fBCOMMANDS\fR | \fBFILES\fR]
.SH DESCRIPTION
\fBhash\fR is minimalistic command line intepreter for unix and unix-like systems that executes commands read from the standard input or from a file.
.SH OPTIONS
\fBhash\fR handles the following options:
.TP
.P
\fB--help\fR \tDisplay a usage message on standard output and exit
successfully.
.SH AUTHORS
Written by Leo Emaxie
